package com.room.game.stage1

enum class Event {
    SCREWDRIVER_TAKEN,
    KEY_FROM_SNOWMAN_TAKEN,
    PHONE_FROM_LOCKER_TAKEN,
    CHARGER_TAKEN,

    LOCKER_LOCK_CLICKED,
    PHONE_HOLDER_CLICKED,
    FIX_BUG_BUTTON_CLICKED,
    LEFT_SCREW_UNSCREWED,
    RIGHT_SCREW_UNSCREWED,
    ROUTER_CLICKED,
    DEPLOY_BUTTON_CLICKED,

    LOCKER_CLICKED,
    POWER_SOCKET_ITEM_CLICKED,
    NOTEBOOK_CLICKED,
    DESK_LOCKER_ITEM_CLICKED,
    MARKERS_CLICKED,

    LEFT_ARROW_CLICKED,
    RIGHT_ARROW_CLICKED,
    DOWN_ARROW_CLICKED,

    INVENTORY_PHONE_CLICKED,
    INVENTORY_KEY_CLICKED,
    INVENTORY_SCREWDRIVER_CLICKED,
    INVENTORY_CHARGER_CLICKED
}
