package com.room.game.stage1

enum class Event {

    // Title screen

    START_GAME,
    ICON_MUSIC_CLICKED,

    // Tablet screen

    NUMBER_1_BUTTON_CLICKED,
    NUMBER_2_BUTTON_CLICKED,
    NUMBER_3_BUTTON_CLICKED,
    NUMBER_4_BUTTON_CLICKED,
    NUMBER_5_BUTTON_CLICKED,
    NUMBER_6_BUTTON_CLICKED,
    NUMBER_7_BUTTON_CLICKED,
    NUMBER_8_BUTTON_CLICKED,
    NUMBER_9_BUTTON_CLICKED,
    ENTER_BUTTON_CLICKED,

    // Whiteboard screen

    LEFT_SCREW_CLICKED,
    RIGHT_SCREW_CLICKED,
    TV_CLICKED,
    MESSAGE_134_CLICKED,
    WHITEBOARD_IMAGE_CLICKED,
    WHITEBOARD_NOTE_CLICKED,
    BROKEN_TV_CLICKED,
    TV_ON_ONE_SCREW_CLICKED,

    // Snowman screen

    BLOHAJ_CLICKED,
    KEY_FROM_SNOWMAN_CLICKED,
    SNOWMAN_CLICKED,

    // Locker screen

    PHONE_IN_LOCKER_CLICKED,
    LOCKER_DOOR_CLICKED,
    TABLET_CLICKED,

    // Workplace screen

    CHARGER_CLICKED,
    PHONE_HOLDER_CLICKED,
    CONNECTED_PHONE_CLICKED,
    DEPLOY_BUTTON_CLICKED,
    POWER_SOCKET_ITEM_CLICKED,
    NOTEBOOK_CLICKED,
    DESK_LOCKER_ITEM_CLICKED,

    // UI

    LEFT_ARROW_CLICKED,
    RIGHT_ARROW_CLICKED,
    DOWN_ARROW_CLICKED,

    // Inventory

    INVENTORY_PHONE_CLICKED,
    INVENTORY_KEY_CLICKED,
    INVENTORY_SCREWDRIVER_CLICKED,
    INVENTORY_CHARGER_CLICKED
}
