package com.room.game.stage1

enum class Event {

    // TitleScreen

    START_GAME,
    ICON_MUSIC_CLICKED,
    ICON_SOUND_CLICKED,

    // Tablet screen

    NUMBER_1_BUTTON_CLICKED,
    NUMBER_2_BUTTON_CLICKED,
    NUMBER_3_BUTTON_CLICKED,
    NUMBER_4_BUTTON_CLICKED,
    NUMBER_5_BUTTON_CLICKED,
    NUMBER_6_BUTTON_CLICKED,
    NUMBER_7_BUTTON_CLICKED,
    NUMBER_8_BUTTON_CLICKED,
    NUMBER_9_BUTTON_CLICKED,

    // Notebook screen
    FIX_BUG_BUTTON_CLICKED,
    DEPLOY_BUTTON_CLICKED,
    REFRESH_BUTTON_CLICKED,

    SCREWDRIVER_TAKEN,
    KEY_FROM_SNOWMAN_TAKEN,
    PHONE_FROM_LOCKER_TAKEN,
    CHARGER_TAKEN,

    TABLET_CLICKED,
    PHONE_HOLDER_CLICKED,
    LEFT_SCREW_UNSCREWED,
    RIGHT_SCREW_UNSCREWED,
    ROUTER_CLICKED,

    LOCKER_CLICKED,
    POWER_SOCKET_ITEM_CLICKED,
    NOTEBOOK_CLICKED,
    DESK_LOCKER_ITEM_CLICKED,
    MARKERS_CLICKED,

    LEFT_ARROW_CLICKED,
    RIGHT_ARROW_CLICKED,
    DOWN_ARROW_CLICKED,

    INVENTORY_PHONE_CLICKED,
    INVENTORY_KEY_CLICKED,
    INVENTORY_SCREWDRIVER_CLICKED,
    INVENTORY_CHARGER_CLICKED
}
